### ISSUE TITLE
[bug] Compare function

### ISSUE THREAD

**Issue by folkvir** [gurisko/sorted-array#1]
The compare function loaded in the constructor is not correctly loaded. And of course, never called.  

```js
import SortedArray from '...'

function cmp (a, b) {
 console.log('sorted: ', a, b)
 return a - b
}

const a = new SortedArray(cmp)

a.insert(2) // no log
a.insert(1) // no log

a.cmp = cmp

a.insert(3) // LOG
````
Workaround done.

**Comment by gurisko** [comment]
Hi @folkvir . Thank you for reporting this issue.

However, I don't see a bug. Compare function does not have to be executed at all times.

**Comment by folkvir** [comment]
Actually it works now. Bizarre things. Sorry for this useless Issue.
